version: '3.4'

services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./templates:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  samba:
    image: dperson/samba:latest
    container_name: samba
    tty: true
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    stdin_open: true
    environment:
      TZ: 'America/Lima'
    networks:
      - default
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./files:/samba/files
    command: '-u "alexpi;password;1000;alexpi;1000" -s "AlexPiDocs;/samba/files/alexpi;yes;no;yes;alexpi;alexpi;Alexpi documents"'

networks:
  default: