version: '3.4'

services:
  samba:
    image: dperson/samba:rpi
    container_name: samba
    tty: true
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    stdin_open: true
    environment:
      TZ: 'America/Lima'
    networks:
      - default
  #   read_only: true
  #   tmpfs:
  #     - /tmp
    volumes:
      - ./samba/files:/samba/files
    command: '-s "AlexPi-Docs:/samba/files/alexpi;yes;no;no;alexpi;alexpi;;Alexpi documents" -u "alexpi;password;1000;alexpi;1000" '

networks:
  default: